// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Wonka from "wonka/src/wonka.js";
import * as Api from "@aws-amplify/api";
import * as Index from "@aws-amplify/pubsub/lib-esm/index";

function configure(config) {
  Api.default.configure(config);
  Index.default.configure(config);
  return /* () */0;
}

function listener_next($$event) {
  console.log("Subscription: ", JSON.stringify($$event.value.data, null, 2));
  console.log("EVENT: ", JSON.stringify($$event, null, 2));
  var message = $$event.value.data.message;
  console.log("MESSAGE: ", JSON.stringify(message, null, 2));
  return /* () */0;
}

function listener_error(errorValue) {
  console.log(errorValue);
  return /* () */0;
}

function listener_complete(param) {
  console.log("COMPLETE");
  return /* () */0;
}

var listener = {
  next: listener_next,
  error: listener_error,
  complete: listener_complete
};

function mutate(graphqlOperation) {
  return Api.default.graphql(graphqlOperation);
}

function query(graphqlOperation) {
  return Api.default.graphql(graphqlOperation);
}

function subscribe(graphqlOperation) {
  return Api.default.graphql(graphqlOperation);
}

function subscribeToObservable(graphqlOperation) {
  return Wonka.fromObservable(Api.default.graphql(graphqlOperation));
}

function extractMessageFrom($$event) {
  return $$event.value.data.onCreateMessage.message;
}

function extractCommentFrom($$event) {
  return $$event.value.data.comment.message;
}

function subscribeToComment(graphqlOperation) {
  return Wonka.map(extractCommentFrom)(Wonka.fromObservable(Api.default.graphql(graphqlOperation)));
}

function subscribeToMessage(graphqlOperation) {
  return Wonka.map(extractMessageFrom)(Wonka.fromObservable(Api.default.graphql(graphqlOperation)));
}

function subscribeToMessage2(graphqlOperation) {
  return Wonka.fromObservable(Api.default.graphql(graphqlOperation));
}

var Types = /* alias */0;

export {
  Types ,
  configure ,
  listener ,
  mutate ,
  query ,
  subscribe ,
  subscribeToObservable ,
  extractMessageFrom ,
  extractCommentFrom ,
  subscribeToComment ,
  subscribeToMessage ,
  subscribeToMessage2 ,
  
}
/* Wonka Not a pure module */
