// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as DataJson from "./data.json";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as AwsExportsJs from "./aws-exports.js";

var complex = DataJson;

var config = AwsExportsJs.default;

function decodeConfig(json) {
  return {
          aws_project_region: Json_decode.field("aws_project_region", Json_decode.string, json),
          aws_cognito_identity_pool_id: Json_decode.field("aws_cognito_identity_pool_id", Json_decode.string, json),
          aws_cognito_region: Json_decode.field("aws_cognito_region", Json_decode.string, json),
          aws_user_pools_id: Json_decode.field("aws_user_pools_id", Json_decode.string, json),
          aws_user_pools_web_client_id: Json_decode.field("aws_user_pools_web_client_id", Json_decode.string, json),
          aws_appsync_graphqlEndpoint: Json_decode.field("aws_appsync_graphqlEndpoint", Json_decode.string, json),
          aws_appsync_region: Json_decode.field("aws_appsync_region", Json_decode.string, json),
          aws_appsync_authenticationType: Json_decode.field("aws_appsync_authenticationType", Json_decode.string, json)
        };
}

var config$1 = decodeConfig(config);

var url = config$1.aws_appsync_graphqlEndpoint;

var region = config$1.aws_appsync_region;

var type_ = config$1.aws_appsync_authenticationType;

var jwtToken = "BBAALKG";

var c = {
  url: url,
  region: region,
  auth: {
    type: type_,
    jwtToken: jwtToken
  }
};

var C = {
  url: url,
  region: region,
  type_: type_,
  jwtToken: jwtToken,
  c: c
};

var a = {
  clientOptions: c,
  complexObjectsCredentials: complex
};

console.log(a);

export {
  complex ,
  decodeConfig ,
  config$1 as config,
  C ,
  a ,
  
}
/* complex Not a pure module */
