// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Theme from "../Theme.bs.js";
import * as React from "react";
import * as ReactNative from "react-native";
import * as VectorIcons from "@expo/vector-icons";

var filter = require("./Icons/filter.png");

var settings = require("./Icons/settings.png");

var home = require("./Icons/home.png");

var message = require("./Icons/message.png");

var notification = require("./Icons/notification.png");

var search = require("./Icons/search.png");

var compose = require("./Icons/compose.png");

var avatar = {
  uri: "https://github.com/reasonml-community.png"
};

var Ionicons = { };

var FontAwesome5 = { };

function Icons$IconShell(Props) {
  var name = Props.name;
  var match = Props.size;
  var size = match !== undefined ? match : 20;
  var tintColor = Theme.Colors.highlight;
  return React.createElement(ReactNative.View, {
              children: React.createElement(VectorIcons.FontAwesome5, {
                    name: name,
                    color: tintColor,
                    size: size
                  })
            });
}

var IconShell = {
  make: Icons$IconShell
};

export {
  filter ,
  settings ,
  home ,
  message ,
  notification ,
  search ,
  compose ,
  avatar ,
  Ionicons ,
  FontAwesome5 ,
  IconShell ,
  
}
/* filter Not a pure module */
