// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ProfileStyle from "./ProfileStyle.bs.js";
import * as ReactNative from "react-native";

function Form(Props) {
  var onChange = Props.onChange;
  var twitter = Props.twitter;
  var github = Props.github;
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(ReactNative.View, {
                  children: React.createElement(ReactNative.TextInput, {
                        autoCapitalize: "none",
                        autoCorrect: false,
                        onChangeText: (function (value) {
                            return Curry._2(onChange, "twitter", value);
                          }),
                        value: twitter,
                        style: ProfileStyle.styles.input
                      })
                }), React.createElement(ReactNative.View, {
                  children: React.createElement(ReactNative.TextInput, {
                        autoCapitalize: "none",
                        autoCorrect: false,
                        onChangeText: (function (value) {
                            return Curry._2(onChange, "github", value);
                          }),
                        value: github,
                        style: ProfileStyle.styles.input
                      })
                }));
}

var make = Form;

export {
  make ,
  
}
/* react Not a pure module */
