// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Theme from "../../Theme.bs.js";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      buttonContainer: {
        flexDirection: "row"
      },
      button: {
        borderColor: Theme.Colors.highlight,
        borderWidth: 1,
        alignItems: "center",
        height: 35,
        justifyContent: "center",
        marginLeft: -1,
        marginRight: 15,
        marginTop: 15,
        width: 110
      },
      buttonText: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.primary,
        fontSize: 13,
        marginTop: 3
      },
      input: {
        color: "rgba(255, 255, 255, .5)",
        fontFamily: Theme.Typography.primary,
        fontSize: 18,
        borderBottomColor: Theme.Colors.highlight,
        borderBottomWidth: 2,
        height: 45,
        marginBottom: 8,
        width: Theme.dimensions.width - 30
      },
      twitterHandle: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.primary,
        fontSize: 18,
        marginLeft: 15
      },
      iconContainer: {
        alignItems: "center",
        flexDirection: "row",
        marginTop: 5
      },
      gitHub: {
        marginTop: 1
      },
      container: {
        backgroundColor: Theme.Colors.primary2,
        flex: 1
      },
      profileContainer: {
        padding: 20
      },
      username: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.primary,
        fontSize: 26,
        marginBottom: 3
      },
      email: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.primary,
        fontSize: 18,
        marginBottom: 10
      }
    });

var logo = Theme.logo;

var dimensions = Theme.dimensions;

var primaryText = Theme.primaryText;

var Colors = Theme.Colors;

var Typography = Theme.Typography;

export {
  logo ,
  dimensions ,
  primaryText ,
  Colors ,
  Typography ,
  styles ,
  
}
/* styles Not a pure module */
