// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Theme from "../../Theme.bs.js";
import * as React from "react";
import * as ProfileStyle from "./ProfileStyle.bs.js";
import * as ReactNative from "react-native";
import * as Ionicons from "@expo/vector-icons";

function Social(Props) {
  var github = Props.github;
  var twitter = Props.twitter;
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(ReactNative.View, {
                  style: ProfileStyle.styles.iconContainer,
                  children: null
                }, React.createElement(Ionicons.Ionicons, {
                      name: "logo-twitter",
                      size: 29,
                      color: Theme.Colors.highlight
                    }), React.createElement(ReactNative.Text, {
                      style: ProfileStyle.styles.twitterHandle,
                      children: twitter
                    })), React.createElement(ReactNative.View, {
                  style: ProfileStyle.styles.iconContainer,
                  children: null
                }, React.createElement(Ionicons.Ionicons, {
                      name: "logo-github",
                      size: 29,
                      color: "white"
                    }), React.createElement(ReactNative.Text, {
                      style: ProfileStyle.styles.twitterHandle,
                      children: github
                    })));
}

var make = Social;

export {
  make ,
  
}
/* Theme Not a pure module */
