// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Core from "@aws-amplify/core";

function levelToString(param) {
  switch (param) {
    case /* Error */0 :
        return "ERROR";
    case /* Warn */1 :
        return "WARN";
    case /* Info */2 :
        return "INFO";
    case /* Verbose */3 :
        return "VERBOSE";
    case /* Debug */4 :
        return "DEBUG";
    case /* Silly */5 :
        return "SILLY";
    
  }
}

function createLogger(name, level, param) {
  var tmp = { };
  if (name !== undefined) {
    tmp.name = Caml_option.valFromOption(name);
  }
  var tmp$1 = Belt_Option.map(level, levelToString);
  if (tmp$1 !== undefined) {
    tmp.level = Caml_option.valFromOption(tmp$1);
  }
  return new Core.Logger(tmp);
}

var logger = createLogger("UserProvider", /* Info */2, /* () */0);

function log(level, message) {
  logger.log(levelToString(level), message);
  return /* () */0;
}

function logO(level, message) {
  logger.log(levelToString(level), message);
  return /* () */0;
}

export {
  levelToString ,
  createLogger ,
  logger ,
  log ,
  logO ,
  
}
/* logger Not a pure module */
