// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactNative from "react-native";
import * as DiscussionStyle from "./DiscussionStyle.bs.js";

function CommentInput(Props) {
  var message = Props.message;
  var handleChangeText = Props.handleChangeText;
  Props.createComment;
  return React.createElement(ReactNative.View, {
              children: React.createElement(ReactNative.TextInput, {
                    autoCapitalize: "none",
                    autoCorrect: false,
                    onChangeText: (function (value) {
                        return Curry._1(handleChangeText, (function (param) {
                                      return value;
                                    }));
                      }),
                    onSubmitEditing: (function (param) {
                        return /* () */0;
                      }),
                    placeholder: "Discuss this talk.",
                    value: message,
                    style: DiscussionStyle.styles.input
                  })
            });
}

var make = CommentInput;

export {
  make ,
  
}
/* react Not a pure module */
