// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as DateFns from "bs-date-fns/src/DateFns.js";
import * as ArrayUtils from "../utils/ArrayUtils.bs.js";
import * as DifferenceInSeconds from "date-fns/differenceInSeconds";

function make(id, message, createdAt, createdBy, talkId, deviceId, param) {
  return {
          id: id,
          talkId: talkId,
          message: message,
          createdAt: createdAt,
          createdBy: createdBy,
          deviceId: deviceId
        };
}

function id(t) {
  return t.id;
}

function message(t) {
  return t.message;
}

function createdAt(t) {
  return t.createdAt;
}

function createdBy(t) {
  return t.createdBy;
}

function createdAtPretty(t) {
  return DateFns.format("MMMM D, YYYY", t.createdAt);
}

function sort(comments) {
  return ArrayUtils.copyAndSort((function (x, y) {
                return DifferenceInSeconds(y.createdAt, x.createdAt) | 0;
              }), comments);
}

function makeFromJs(comment) {
  var partial_arg = comment.createdBy;
  var partial_arg$1 = (function (eta) {
        return DateFns.parseString(undefined, eta);
      })(comment.createdAt);
  var partial_arg$2 = comment.message;
  var partial_arg$3 = comment.id;
  var func = function (param, param$1, param$2) {
    return make(partial_arg$3, partial_arg$2, partial_arg$1, partial_arg, param, param$1, param$2);
  };
  var arg = comment.deviceId;
  return (function (param) {
      return Curry._2(func, param, arg);
    });
}

export {
  make ,
  id ,
  message ,
  createdAt ,
  createdBy ,
  createdAtPretty ,
  sort ,
  makeFromJs ,
  
}
/* DateFns Not a pure module */
