// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as NavigationOptions$ReactNavigation from "reason-react-navigation/src/NavigationOptions.bs.js";

var Header = NavigationOptions$ReactNavigation.Header;

var HeaderTitle = NavigationOptions$ReactNavigation.HeaderTitle;

var TabBarIcon = NavigationOptions$ReactNavigation.TabBarIcon;

var TabBarLabel = NavigationOptions$ReactNavigation.TabBarLabel;

var DrawerIcon = NavigationOptions$ReactNavigation.DrawerIcon;

var DrawerLabel = NavigationOptions$ReactNavigation.DrawerLabel;

export {
  Header ,
  HeaderTitle ,
  TabBarIcon ,
  TabBarLabel ,
  DrawerIcon ,
  DrawerLabel ,
  
}
/* No side effect */
