// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as TabNavigator$ReactNavigation from "reason-react-navigation/src/TabNavigator.bs.js";

var MaterialTop = TabNavigator$ReactNavigation.MaterialTop;

var Bottom = TabNavigator$ReactNavigation.Bottom;

export {
  MaterialTop ,
  Bottom ,
  
}
/* No side effect */
