// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Theme from "../styles/Theme.bs.js";
import * as React from "react";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      container: {
        backgroundColor: "rgba(18, 25, 50, 1)",
        alignItems: "center",
        height: 88
      },
      logo: {
        bottom: 7,
        height: 35,
        left: 10,
        position: "absolute",
        width: 120
      }
    });

function BaseHeader(Props) {
  return React.createElement(ReactNative.View, {
              style: styles.container,
              children: React.createElement(ReactNative.Image, {
                    resizeMode: "contain",
                    source: Theme.logo,
                    style: styles.logo
                  })
            });
}

var make = BaseHeader;

var $$default = BaseHeader;

export {
  styles ,
  make ,
  $$default ,
  $$default as default,
  
}
/* styles Not a pure module */
