// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

function LoadingScreen(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.View, {
                  style: {
                    alignItems: "center",
                    flex: 1,
                    justifyContent: "center"
                  },
                  children: React.createElement(ReactNative.Text, {
                        children: "Loading"
                      })
                }));
}

var make = LoadingScreen;

export {
  make ,
  
}
/* react Not a pure module */
