// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Theme from "../Theme.bs.js";
import * as React from "react";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      logoContainer: {
        alignItems: "center",
        justifyContent: "center",
        marginTop: 70
      },
      logo: {
        height: 50,
        width: 200
      }
    });

function Logo(Props) {
  return React.createElement(ReactNative.View, {
              style: styles.logoContainer,
              children: React.createElement(ReactNative.Image, {
                    resizeMode: "contain",
                    source: Theme.logo,
                    style: styles.logo
                  })
            });
}

var make = Logo;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
