// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Theme from "../Theme.bs.js";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      headerStyle: {
        backgroundColor: Theme.Colors.primary,
        borderBottomColor: Theme.Colors.primaryLight,
        borderBottomWidth: 1
      },
      bottomButton: {
        borderTopWidth: 1,
        alignItems: "center",
        height: 45,
        justifyContent: "center",
        width: Theme.dimensions.width / 2
      },
      bottomButtonText: {
        color: Theme.Colors.highlight,
        fontFamily: Theme.Typography.primary
      },
      tabBottomContainer: {
        borderBottomColor: "rgba(255, 255, 255, .2)",
        borderBottomWidth: 1,
        borderTopColor: "rgba(255, 255, 255, .2)",
        borderTopWidth: 1,
        bottom: -1,
        flexDirection: "row",
        left: 0,
        position: "absolute",
        width: Theme.dimensions.width
      },
      listContainer: {
        paddingBottom: 70
      },
      speakerContainer: {
        flexDirection: "row",
        paddingBottom: 10,
        paddingHorizontal: 15
      },
      logo: {
        height: 35,
        marginBottom: 4,
        marginLeft: 10,
        width: 120
      },
      container: {
        backgroundColor: Theme.Colors.primaryLight,
        flex: 1
      },
      loading: {
        backgroundColor: Theme.Colors.primaryLight,
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      talk: {
        backgroundColor: Theme.Colors.primary,
        borderRadius: 10,
        margin: 15,
        marginBottom: 0,
        paddingBottom: 0,
        paddingTop: 15
      },
      timeContainer: {
        backgroundColor: Theme.Colors.primaryDark,
        borderBottomLeftRadius: 15,
        borderBottomRightRadius: 15,
        paddingHorizontal: 20,
        paddingVertical: 15
      },
      talkTime: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.primary
      },
      infoContainer: {
        flex: 8,
        paddingLeft: 20
      },
      name: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.medium,
        fontSize: 17,
        fontWeight: "bold",
        marginBottom: 5
      },
      avatarContainer: {
        borderRadius: 4,
        flex: 2,
        flexDirection: "row",
        justifyContent: "flex-start",
        overflow: "hidden"
      },
      avatar: {
        height: 70,
        width: 60
      },
      speakerName: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.primary,
        fontSize: 14
      }
    });

var logo = Theme.logo;

var dimensions = Theme.dimensions;

var primaryText = Theme.primaryText;

var Colors = Theme.Colors;

var Typography = Theme.Typography;

export {
  logo ,
  dimensions ,
  primaryText ,
  Colors ,
  Typography ,
  styles ,
  
}
/* styles Not a pure module */
