// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";
import * as ScheduleStyle from "./ScheduleStyle.bs.js";

function ScheduleItem(Props) {
  var talk = Props.talk;
  var onPress = Props.onPress;
  return React.createElement(ReactNative.TouchableOpacity, {
              onPress: onPress,
              children: React.createElement(ReactNative.View, {
                    style: ScheduleStyle.styles.talk,
                    children: null
                  }, React.createElement(ReactNative.View, {
                        style: ScheduleStyle.styles.speakerContainer,
                        children: null
                      }, React.createElement(ReactNative.View, {
                            style: ScheduleStyle.styles.avatarContainer,
                            children: Belt_Option.getWithDefault(Belt_Option.map(talk.speakerAvatar, (function (speakerAvatar) {
                                        return React.createElement(ReactNative.Image, {
                                                    resizeMode: "cover",
                                                    source: {
                                                      uri: speakerAvatar
                                                    },
                                                    style: ScheduleStyle.styles.avatar
                                                  });
                                      })), null)
                          }), React.createElement(ReactNative.View, {
                            style: ScheduleStyle.styles.infoContainer,
                            children: null
                          }, React.createElement(ReactNative.Text, {
                                style: ScheduleStyle.styles.name,
                                children: talk.name
                              }), React.createElement(ReactNative.Text, {
                                style: ScheduleStyle.styles.speakerName,
                                children: talk.speakerName
                              }))), React.createElement(ReactNative.View, {
                        style: ScheduleStyle.styles.timeContainer,
                        children: Belt_Option.getWithDefault(Belt_Option.map(talk.time, (function (time) {
                                    return React.createElement(ReactNative.Text, {
                                                style: ScheduleStyle.styles.talkTime,
                                                children: time
                                              });
                                  })), null)
                      }))
            });
}

var make = ScheduleItem;

export {
  make ,
  
}
/* react Not a pure module */
