// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Theme from "../Theme.bs.js";
import * as React from "react";
import * as ReactNative from "react-native";
import * as FontAwesome from "@expo/vector-icons";

var tintColor = Theme.Colors.highlight;

function TabIcon(Props) {
  var name = Props.name;
  var match = Props.size;
  var size = match !== undefined ? match : 20;
  var match$1 = Props.color;
  var color = match$1 !== undefined ? match$1 : tintColor;
  return React.createElement(ReactNative.View, {
              children: React.createElement(FontAwesome.FontAwesome, {
                    name: (function () {
                          switch (name) {
                            case -14065986 :
                                return "calendar";
                            case 5442204 :
                                return "map";
                            case -844262837 :
                                return "user";
                            
                          }
                        })(),
                    size: size,
                    color: color
                  })
            });
}

var make = TabIcon;

export {
  tintColor ,
  make ,
  
}
/* Theme Not a pure module */
