// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";

var UnsafeFindFailed = Caml_exceptions.create("ArrayUtils.UnsafeFindFailed");

function copyAndSort(f, t) {
  var cp = $$Array.copy(t);
  $$Array.sort(f, cp);
  return cp;
}

function isEmpty(a) {
  return a.length === 0;
}

function isNotEmpty(a) {
  return !isEmpty(a);
}

function flatten(t) {
  return $$Array.of_list(List.flatten($$Array.to_list(t)));
}

export {
  UnsafeFindFailed ,
  copyAndSort ,
  isEmpty ,
  isNotEmpty ,
  flatten ,
  
}
/* No side effect */
