// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Theme from "../../Theme.bs.js";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      avatar: {
        borderRadius: 15,
        height: 300,
        width: Theme.dimensions.width - 40
      },
      container: {
        backgroundColor: Theme.Colors.primaryLight,
        flex: 1,
        padding: 30
      },
      title: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.medium,
        fontSize: 22,
        marginTop: 15
      },
      name: {
        color: Theme.Colors.highlight,
        fontFamily: Theme.Typography.medium,
        fontSize: 26,
        marginBottom: 20,
        marginTop: 20
      },
      speakerName: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.medium,
        fontSize: 16,
        marginBottom: 5
      },
      time: {
        color: Theme.Colors.highlight,
        fontFamily: Theme.Typography.medium
      },
      summary: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.primary,
        marginTop: 4
      },
      speakerBio: {
        color: Theme.Colors.primaryText
      }
    });

var logo = Theme.logo;

var dimensions = Theme.dimensions;

var primaryText = Theme.primaryText;

var Colors = Theme.Colors;

var Typography = Theme.Typography;

export {
  logo ,
  dimensions ,
  primaryText ,
  Colors ,
  Typography ,
  styles ,
  
}
/* styles Not a pure module */
