// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TalkType from "../../models/TalkType.bs.js";
import * as TalkStyles from "./TalkStyles.bs.js";
import * as ReactNative from "react-native";

function Talk(Props) {
  var navigation = Props.navigation;
  var getTalk = navigation.getParam("talk");
  var talk = TalkType.talkJson(getTalk);
  var match = talk.speakerAvatar;
  var match$1 = talk.time;
  return React.createElement(ReactNative.ScrollView, {
              children: React.createElement(ReactNative.View, {
                    style: TalkStyles.styles.container,
                    children: null
                  }, match !== undefined ? React.createElement(ReactNative.Image, {
                          resizeMode: "cover",
                          source: {
                            uri: match
                          },
                          style: TalkStyles.styles.avatar
                        }) : null, React.createElement(ReactNative.Text, {
                        style: TalkStyles.styles.name,
                        children: talk.name
                      }), React.createElement(ReactNative.Text, {
                        style: TalkStyles.styles.speakerName,
                        children: talk.speakerName
                      }), match$1 !== undefined ? React.createElement(ReactNative.Text, {
                          style: TalkStyles.styles.time,
                          children: match$1
                        }) : null, React.createElement(ReactNative.Text, {
                        style: TalkStyles.styles.title,
                        children: "Summary"
                      }), React.createElement(ReactNative.Text, {
                        style: TalkStyles.styles.summary,
                        children: talk.summary
                      }), React.createElement(ReactNative.Text, {
                        style: TalkStyles.styles.title,
                        children: "Bio"
                      }), React.createElement(ReactNative.Text, {
                        style: TalkStyles.styles.speakerBio,
                        children: talk.speakerBio
                      }))
            });
}

var make = Talk;

export {
  make ,
  
}
/* react Not a pure module */
