// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Json from "@glennsl/bs-json/src/Json.bs.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as Caml_js_exceptions from "bs-platform/lib/es6/caml_js_exceptions.js";

function decodeJwt(json) {
  return {
          jwtToken: Json_decode.field("jwtToken", Json_decode.string, json)
        };
}

function decodeToken(json) {
  return {
          idToken: Json_decode.field("idToken", decodeJwt, json)
        };
}

function response(json) {
  try {
    return /* Ok */Block.__(0, [decodeToken(Json.parseOrRaise(json))]);
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e[0] === Json_decode.DecodeError) {
      return /* Error */Block.__(1, [e[1]]);
    } else {
      return /* Error */Block.__(1, [String(e)]);
    }
  }
}

var Decode = {
  decodeJwt: decodeJwt,
  decodeToken: decodeToken,
  response: response
};

function test(res) {
  console.log(response(res));
  return /* () */0;
}

export {
  Decode ,
  test ,
  
}
/* No side effect */
