// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as ReactNative from "react-native";
import * as DiscussionStyle from "./discussion/DiscussionStyle.bs.js";

function DiscussionHistory(Props) {
  var comments = Props.comments;
  var match = comments.length > 1;
  var tmp;
  if (match) {
    var match$1 = comments.length === 0;
    tmp = React.createElement(ReactNative.ScrollView, {
          children: null
        }, match$1 ? React.createElement(ReactNative.View, {
                style: DiscussionStyle.styles.comment,
                children: React.createElement(ReactNative.Text, {
                      style: DiscussionStyle.styles.message,
                      children: "No comments yet!"
                    })
              }) : null, Belt_Array.mapWithIndex(comments, (function (idx, c) {
                return React.createElement(ReactNative.View, {
                            style: DiscussionStyle.styles.comment,
                            children: null,
                            key: String(idx)
                          }, React.createElement(ReactNative.Text, {
                                style: DiscussionStyle.styles.message,
                                children: "message: " + c.message
                              }), React.createElement(ReactNative.Text, {
                                style: DiscussionStyle.styles.createdBy,
                                children: "createdBy: " + c.createdBy
                              }), React.createElement(ReactNative.Text, {
                                style: DiscussionStyle.styles.createdBy,
                                children: "createdAt: " + c.createdAt
                              }));
              })));
  } else {
    tmp = React.createElement(ReactNative.View, {
          style: DiscussionStyle.styles.comment,
          children: React.createElement(ReactNative.Text, {
                style: DiscussionStyle.styles.message,
                children: "No comments yet!"
              })
        });
  }
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNative.View, {
                  style: DiscussionStyle.styles.scrollViewContainer,
                  children: tmp
                }));
}

var make = DiscussionHistory;

export {
  make ,
  
}
/* react Not a pure module */
