// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Theme from "./Theme.bs.js";
import * as React from "react";
import * as Helpers from "./utils/Helpers.bs.js";
import * as BaseHeader from "./BaseHeader.bs.js";
import * as ReactNative from "react-native";
import * as MapView from "react-native-maps/lib/components/MapView";
import * as MapMarker from "react-native-maps/lib/components/MapMarker";

var styles = ReactNative.StyleSheet.create({
      mapStyle: {
        borderRadius: 5,
        height: 400,
        width: Theme.dimensions.width - 40
      },
      addressContainer: {
        paddingVertical: 20
      },
      address: {
        color: Theme.Colors.primaryText,
        fontFamily: Theme.Typography.primary,
        fontSize: 18,
        marginBottom: 4
      },
      addressHeading: {
        color: Theme.Colors.highlight,
        fontSize: 18,
        fontWeight: "500",
        marginBottom: 5
      },
      rocketView: {
        fontSize: 24
      },
      container: {
        backgroundColor: Theme.Colors.primary2,
        flex: 1
      },
      mapContainer: {
        flex: 1
      },
      mapView: {
        padding: 20
      }
    });

var rocketIcon = "🚀";

function $$Map(Props) {
  return React.createElement(ReactNative.View, {
              style: styles.container,
              children: null
            }, React.createElement(BaseHeader.make, { }), React.createElement(ReactNative.View, {
                  style: styles.mapContainer,
                  children: React.createElement(ReactNative.ScrollView, {
                        children: React.createElement(ReactNative.View, {
                              style: styles.mapView,
                              children: null
                            }, React.createElement(MapView.default, {
                                  region: {
                                    latitude: 37.78825,
                                    longitude: -122.4324,
                                    latitudeDelta: 0.0922,
                                    longitudeDelta: 0.0421
                                  },
                                  initialRegion: {
                                    latitude: 37.78825,
                                    longitude: -122.4324,
                                    latitudeDelta: 0.0922,
                                    longitudeDelta: 0.0421
                                  },
                                  style: styles.mapStyle,
                                  children: React.createElement(MapMarker.default, {
                                        coordinate: {
                                          latitude: 37.78825,
                                          longitude: -122.4324
                                        },
                                        children: React.createElement(ReactNative.View, {
                                              children: React.createElement(ReactNative.Text, {
                                                    style: styles.rocketView,
                                                    children: rocketIcon
                                                  })
                                            })
                                      })
                                }), React.createElement(ReactNative.TouchableHighlight, {
                                  underlayColor: "transparent",
                                  onPress: (function (_e) {
                                      ReactNative.Linking.openURL("https://goo.gl/maps/DNrmyCTQPDC5RkHc9").then((function (param) {
                                              return Promise.resolve((console.log("opened https://goo.gl/maps/DNrmyCTQPDC5RkHc9"), /* () */0));
                                            }));
                                      return /* () */0;
                                    }),
                                  children: React.createElement(ReactNative.View, {
                                        style: styles.addressContainer,
                                        children: null
                                      }, React.createElement(ReactNative.Text, {
                                            style: /* :: */[
                                              styles.address,
                                              /* :: */[
                                                styles.addressHeading,
                                                /* [] */0
                                              ]
                                            ],
                                            children: "AWS Loft"
                                          }), React.createElement(ReactNative.Text, {
                                            style: styles.address,
                                            children: "525 Market St #2"
                                          }), React.createElement(ReactNative.Text, {
                                            style: styles.address,
                                            children: "San Francisco, CA 94105"
                                          }))
                                }))
                      })
                }));
}

$$Map.navigationOptions = {
  title: "Map",
  tabBarIcon: Helpers.tabBarIcon(/* map */5442204)
};

var logo = Theme.logo;

var dimensions = Theme.dimensions;

var primaryText = Theme.primaryText;

var Colors = Theme.Colors;

var Typography = Theme.Typography;

var make = $$Map;

var $$default = $$Map;

export {
  logo ,
  dimensions ,
  primaryText ,
  Colors ,
  Typography ,
  styles ,
  rocketIcon ,
  make ,
  $$default ,
  $$default as default,
  
}
/* styles Not a pure module */
