// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Talk from "./components/talk/Talk.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Theme from "./Theme.bs.js";
import * as React from "react";
import * as Discussion from "./Discussion.bs.js";
import * as PagerStyle from "./components/pager/PagerStyle.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";

function Pager(Props) {
  var navigation = Props.navigation;
  var match = React.useState((function () {
          return 0;
        }));
  var setIndex = match[1];
  var index = match[0];
  var match$1 = index === 0;
  var match$2 = index === 1;
  return React.createElement(ReactNative.View, {
              style: PagerStyle.styles.container,
              children: null
            }, React.createElement(ReactNative.View, {
                  style: PagerStyle.styles.tabContainer,
                  children: null
                }, React.createElement(ReactNative.TouchableHighlight, {
                      style: PagerStyle.styles.buttonContainer,
                      underlayColor: "transparent",
                      onPress: (function (param) {
                          return Curry._1(setIndex, (function (param) {
                                        return 0;
                                      }));
                        }),
                      children: React.createElement(ReactNative.View, {
                            style: /* array */[
                              Caml_option.some(PagerStyle.styles.button),
                              match$1 ? Caml_option.some(PagerStyle.styles.indexSelected) : Caml_option.some(PagerStyle.styles.indexNotSelected)
                            ],
                            children: React.createElement(ReactNative.Text, {
                                  style: PagerStyle.styles.buttonText,
                                  children: "Talk Info"
                                })
                          })
                    }), React.createElement(ReactNative.TouchableHighlight, {
                      style: PagerStyle.styles.buttonContainer,
                      underlayColor: "transparent",
                      onPress: (function (param) {
                          return Curry._1(setIndex, (function (param) {
                                        return 1;
                                      }));
                        }),
                      children: React.createElement(ReactNative.View, {
                            style: /* array */[
                              Caml_option.some(PagerStyle.styles.button),
                              match$2 ? Caml_option.some(PagerStyle.styles.indexSelected) : Caml_option.some(PagerStyle.styles.indexNotSelected)
                            ],
                            children: React.createElement(ReactNative.Text, {
                                  style: PagerStyle.styles.buttonText,
                                  children: "Discuss"
                                })
                          })
                    })), index !== 0 ? (
                index !== 1 ? null : React.createElement(Discussion.make, {
                        navigation: navigation
                      })
              ) : React.createElement(Talk.make, {
                    navigation: navigation
                  }));
}

Pager.navigationOptions = (function (params) {
    var navigation = params.navigation;
    var title = Belt_Option.mapWithDefault(Caml_option.nullable_to_opt(navigation.getParam("talk")), "Talk", (function (t) {
            return t.name;
          }));
    return {
            title: title,
            headerTintColor: Theme.Colors.highlight
          };
  });

var make = Pager;

export {
  make ,
  
}
/*  Not a pure module */
